filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        simplify_boolean_return: true
        use_self_instead_of_fqcn: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true

coding_style:
    php:
        spaces:
            general:
                linefeed_character: return-newline
            around_operators:
                concatenation: true
            other:
                after_type_cast: false
build: true
tools:
    external_code_coverage: true